services:

# 1. ADK KTP Agent Web Interface
  adk:
    build: .
    container_name: adk-ktp-agent # Change container name
    restart: always
    env_file:
      - .env
    # environment:
    #   - REMOTE_AGENT_URL=http://34.101.127.72:5001
    depends_on:
      - toolbox
    command: >
      adk web
      --host 0.0.0.0
    ports:
      - "8001:8000"
    networks:
      - cloud-sql-network

# 2. ADK API Server
  adk-server:
    build: .
    container_name: adk-server-ktp # Change container name
    restart: always
    env_file:
      - .env
    depends_on:
      - toolbox
    command: >
      adk api_server
      --host 0.0.0.0
      --session_service_uri="postgresql+asyncpg://${CLOUD_SQL_PG_USER}:${CLOUD_SQL_PG_PASSWORD}@cloud-sql-proxy:5432/${CLOUD_SQL_PG_SESSIONDB}"
      --allow_origins="*"
      --artifact_service_uri gs://poc-bjb
      --otel_to_cloud
    ports:
      - "8003:8000"
    networks:
      - cloud-sql-network

# 3. FastAPI Application
  fastapi-app:
    build: .
    container_name: fastapi-app # Change container name
    restart: always
    env_file:
      - .env
    environment:
      - CLOUD_SQL_PG_HOST=cloud-sql-proxy
      - CLOUD_SQL_PG_PORT=5432
    ports:
      - "8004:8004"
    depends_on:
      - adk-server
    command: uv run main.py
    networks:
      - cloud-sql-network

  # 4. MCP Toolbox
  toolbox:
    image: us-central1-docker.pkg.dev/database-toolbox/toolbox/toolbox:0.24.0
    hostname: toolbox
    platform: linux/amd64
    restart: always
    env_file:
      - .env
    ports:
      - "5001:5000"
    volumes:
      - ./tools.yaml:/config/tools.yaml
    command: [ "toolbox", "--tools-file", "/config/tools.yaml", "--address", "0.0.0.0", "--ui" ]
    networks:
      - cloud-sql-network

networks:
  cloud-sql-network:
    external: true